kind: Secret
apiVersion: v1
metadata:
  name: connect-passwords
type: Opaque
# I tried using stringData and put the passwords as literals using the | character
# but that did not work there was an extra space after the character or perhaps line ending
# even though the file is using Unix line endings, so we fallback to using data and base 64 encoding
data:
  server.security.password: bktUVjNnU012NTlyTk9oVFl6eG0=
  db.password: WE9rZ21YeGZYRkVzZE5VT2w0MyE=