version: '3.1'

services:

  db:
    image: ol-mysql:v2
    ports:
      - 3306:3306
    volumes:
      - "db:c:\\ProgramData\\Objectif Lune\\OL Connect\\MySQL\\data"

  connect:
    image: connect-transactional:v1
#    image: connect:2020.2.1
    environment:
      CONNECT_LICENSE_TEST_PRODUCT: 1
      CONNECT_LICENSE_CODE: 492169039744657454
    ports:
      - 9340:9340
    depends_on:
      - db
    volumes:
      - connect-data:c:\users\connectadmin\Connect
      - "connect-prefs:c:\\ProgramData\\Objectif Lune\\OL Connect"
#      - connect-hidden:c:\ProgramData\F5C3S4
#      - connect-hidden:c:\Connect\F5C3S4
#      - "./users:c:\\ProgramData\\Objectif Lune\\OL Connect\\Initialization"
#      - connect-prefs:c:\prefs

volumes:
  db:
  connect-data:
  connect-prefs: