version: '3.1'

services:

  db:
    image: ol-mysql:v2
    ports:
      - 3306:3306
    volumes:
      - "db:c:\\ProgramData\\Objectif Lune\\OL Connect\\MySQL\\data"

  connect:
    image: connect:latest
    environment:
      CONNECT_LICENSE_TEST_PRODUCT: 1
      CONNECT_LICENSE_CODE: 492169039744657454
    ports:
      - 9340:9340
    depends_on:
      - db
    volumes:
      - "connect-data:c:\\users\\connectadmin\\Connect"
      - "connect-prefs:c:\\ProgramData\\Objectif Lune\\OL Connect"
      - ".\\prefs:c:\\ProgramData\\Objectif Lune\\OL Connect\\Initialization\\Preferences"
      - ".\\secrets:c:\\ProgramData\\Objectif Lune\\OL Connect\\Initialization\\Secrets"

volumes:
  db:
  connect-data:
  connect-prefs: